title: 찬송 선반 프로젝트
description: 찬송 선반 프로젝트의 정보, 기술 명세, 그리고 개발 과정을 한글로 기록한 문서 모음입니다.
remote_theme: just-the-docs/just-the-docs
theme: just-the-docs

url: https://HymnShelf.github.io

aux_links:
  Frontend(Github): https://github.com/HymnShelf/hymn-shelf-frontend
  Backend(Github): https://github.com/HymnShelf/hymn-shelf-backend

markdown: kramdown
kramdown:
  input: GFM
